### ISSUE TITLE
no method named `as_json_string`

### ISSUE THREAD

**Issue by hr8** [khonsulabs/justjson#10]
based on this:

https://github.com/khonsulabs/justjson/issues/9#issuecomment-1416219660

I tried this code:

~~~rust
use justjson::Value;

const DATE: &str = r#"
{
   "day": "Sunday",
   "month": "January"
}
"#;

fn main() {
   let object = Value::from_json(DATE).unwrap();
   let day = object["day"].as_json_string().unwrap();
   dbg!(day);
}
~~~

result:

~~~
error[E0599]: no method named `as_json_string` found for enum `Value` in the current scope
  --> src\main.rs:12:28
   |
12 |    let day = object["day"].as_json_string().unwrap();
~~~

the current docs seem to reflect that this function does not exist:

https://khonsulabs.github.io/justjson/main/justjson/enum.Value.html

**Comment by ecton** [comment]
Sorry, that was a typo in the code snippet I provided. I've edited the original snippet -- the method is just `as_string()`.
