### ISSUE TITLE
as_str behavior is undesired

### ISSUE THREAD

**Issue by hr8** [khonsulabs/justjson#11]
Sorry for opening new issue, but the existing issues keep getting closed. Its common courtesy to keep an issue open for at least a day, to allow for discussion, instead of closing immediately. If I use this code:

~~~rust
use justjson::Value;

const DATE: &str = r#"
{
   "day": "Sunday\nMonday",
   "month": "January"
}
"#;

fn main() {
   let object = Value::from_json(DATE).unwrap();
   let day = object["day"].as_str().unwrap();
   dbg!(day);
}
~~~

result:

~~~
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\main.rs:12:37
~~~

compare with same code from another package:

~~~rust
use humphrey_json::Value;

const DATE: &str = r#"
{
   "day": "Sunday\nMonday",
   "month": "January"
}
"#;

fn main() {
   let object = Value::parse(DATE).unwrap();
   let day = object["day"].as_str().unwrap();
   dbg!(day); // day = "Sunday\nMonday"
}
~~~

and another:

~~~rust
use serde_json::Value;

const DATE: &str = r#"
{
   "day": "Sunday\nMonday",
   "month": "January"
}
"#;

fn main() {
   let object: Value = serde_json::from_str(DATE).unwrap();
   let day = object["day"].as_str().unwrap();
   dbg!(day); // day = "Sunday\nMonday"
}
~~~

I know this is documented:

<https://khonsulabs.github.io/justjson/main/justjson/enum.Value.html#method.as_str>

but it seems a curious choice given current alternatives.

**Comment by ecton** [comment]
This is also documented in the crate's readme. This is one of the fundamental design differences between this crate and others. I do not plan on making `justjson` an exact clone of other crates -- that's pointless. The lazy decoding of JSON is the primary reason I developed this crate. I will not be changing this.

**Comment by hr8** [comment]
OK I respect that.

Just to confirm, is your package the ONLY package that offers lazy, or was the thinking that you wanted a package that did lazy and NOTHING ELSE. if the first question is true, then you could keep the lazy, but add non-lazy methods. if the second question is true, then I guess nothing needs to be done.

**Comment by ecton** [comment]
To me, there's no reason to provide an identical implementation to existing crates. If someone wants pre-parsed JSON Values, there are countless crates, several of which my readme's first section recommend. I don't understand the use case where someone is wanting to use my lazy features *and* also use it separately in a non-lazy way. To me, a developer is usually looking for one approach or the other, not both. If someone wants lazy parsing, my crate is great for them. If they want non-lazy parsing, there are plenty of other crates out there.

**Comment by hr8** [comment]
by support both methods, you can increase the audience to this package. you might not be interested to do that.

further, I like your package because it has zero dependencies. however I must have non-lazy parsing. so unless you are inclined to add it as an additional method, then I must choose another option. thanks for the comments.

if it helps, as an example the Go package offers both lazy and non-lazy, similar to what I am suggesting:

- https://godocs.io/encoding/json#Decoder.Token
- https://godocs.io/encoding/json#Decoder.Decode

**Comment by ecton** [comment]
[tinyjson](https://lib.rs/crates/tinyjson) is the crate I would recommend for you. It has no dependencies, and appears to be well tested and maintained -- and even better than my crate, it is beyond a 1.0 release.

I may eventually add this, but it really was not ever the goal of this crate, as there are already many JSON parsers who do exactly what you're looking for.

**Comment by hr8** [comment]
much appreciated for the suggestions. regarding `tinyjson`, its object builder is ugly:

~~~rust
use tinyjson::JsonValue;

fn kv(s: impl Into<String>, v: impl Into<JsonValue>) -> (String, JsonValue) {
    (s.into(), v.into())
}

fn main() {
   let value = JsonValue::Object([
      kv("null", ()),
      kv("boolean", true),
      kv("number", 1.0),
      kv("string", "one".to_string()),
   ].into());
   dbg!(value);
}
~~~

but to be fair, that might be the case for `justjson` as well, I haven't checked it. regarding `json-deserializer`, I need something that can BOTH Unmarshal and Marshal, so I dont think thats an option.
