### ISSUE TITLE
Value: get method and/or Index Trait

### ISSUE THREAD

**Issue by hr8** [khonsulabs/justjson#5]
example `humphrey_json`:

- <https://docs.rs/humphrey_json/latest/humphrey_json/value/enum.Value.html#impl-Index%3CT%3E-for-Value>
- <https://docs.rs/humphrey_json/latest/humphrey_json/value/enum.Value.html#method.get>

example `rust_json`:

<https://docs.rs/rust_json/latest/rust_json/enum.JsonElem.html#impl-Index%3C%26str%3E-for-JsonElem>

example `serde_json`:

- <https://docs.rs/serde_json/latest/serde_json/enum.Value.html#impl-Index%3CI%3E-for-Value>
- <https://docs.rs/serde_json/latest/serde_json/enum.Value.html#method.get>

**Comment by ecton** [comment]
Thank you for the suggestion! This will be in the next release. There are performance considerations for looking up a key in an object, since currently the backing for Object is just a Vec -- I wrote out my ideas for how I'm hoping to address that someday in #7.

**Comment by ecton** [comment]
I've released [v0.2.2](https://github.com/khonsulabs/justjson/releases/tag/v0.2.2) with this new functionality. Thank you again for the request!
