### ISSUE TITLE
Value to String or &str

### ISSUE THREAD

**Issue by hr8** [khonsulabs/justjson#9]
currently it seems quite difficult just to return a normal `String` or `&str`. For example this code:

~~~rust
use justjson::Value;

const DATE: &str = r#"
{
   "day": "Sunday",
   "month": "January"
}
"#;

fn main() {
   let object = Value::from_json(DATE).unwrap();
   let day = object["day"].
      as_string().unwrap().
      as_json_str().unwrap();
   dbg!(day);
}
~~~

requires four method calls (`as_string`, `as_json_str` and two `unwrap`), and even then, its still wrapped:

~~~
[src\main.rs:15] day = Borrowed(
    "Sunday",
)
~~~

here is another crate that does it in two:

~~~rust
use humphrey_json::Value;

const DATE: &str = r#"
{
   "day": "Sunday",
   "month": "January"
}
"#;

fn main() {
   let object = Value::parse(DATE).unwrap();
   let day = object["day"].as_str().unwrap();
   dbg!(day);
}
~~~

and another:

~~~rust
use serde_json::Value;

const DATE: &str = r#"
{
   "day": "Sunday",
   "month": "January"
}
"#;

fn main() {
   let object: Value = serde_json::from_str(DATE).unwrap();
   let day = object["day"].as_str().unwrap();
   dbg!(day);
}
~~~

**Comment by ecton** [comment]
Getting a value as a str is a bit of an anti-pattern, as it will not be able to return any strings that have escape sequences. This is why I overlooked this method. If you were looking to match on the string, this works:

```rust
let is_sunday = object["day"].as_json_string() == Some("Sunday");
```

And the above will work even if there are escape sequences in JSON. Or, if you want to get the value out to store in an object:

```rust
object["day"].as_string().expect("missing day") == "Sunday"
```

Regardless, I've added the API as it is a valid request. To convert to a String, previously you needed to use `object["day"].as_json_string().unwrap().decoded().to_string()`. That was very much an oversight. `JsonString` now implements `Display`, so `to_string()` is available when String is.
